### ISSUE TITLE
Saving some records returns "validation error"

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#963]
needs hotfix: saving impossible, in the server log:

 ```ruby
Completed 500 Internal Server Error in 47ms (ActiveRecord: 8.4ms)
RuntimeError (can't modify frozen String):
lib/marc_source.rb:72:in `strip!'
lib/marc_source.rb:72:in `get_std_title'
app/models/source.rb:337:in `set_object_fields'
lib/marc_controller_actions.rb:320:in `block in included'
```

**Comment by HirschSt** [comment]
proposed tested hotfix see https://github.com/rism-ch/muscat/commit/3296a7838c110e86dab66d7f7fb1f6f14aa60e64
